[project]
name = 'h1st'
version = '0.1.13'

description = 'Human-First AI (H1st)'
readme = {file = 'README.md', content-type = 'text/markdown', charset = 'UTF-8'}

requires-python = '>= 3.8'

license = {text = 'Apache-2.0'}

authors = [
  {name = 'Aitomatic, Inc.', email = 'engineering@aitomatic.com'}
]
maintainers = [
  {name = 'Aitomatic, Inc.', email = 'engineering@aitomatic.com'}
]

keywords = [
  'Human-First',
  'H1st',
  'Artificial Intelligence',
  'A.I.',
  'AI',
]
classifiers = [
  'Development Status :: 4 - Beta',
  'Operating System :: MacOS',
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: Microsoft :: Windows',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.8',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Topic :: Scientific/Engineering',
  'Topic :: Software Development :: Libraries :: Python Modules',
]

dependencies = [
  # Data Processing
  'NumPy >= 1.22.4',   #  not latest, for compat w/ some other common deps
  'Pandas >= 1.4.3',
  'PyArrow >= 9.0.0',
  'PySpark >= 3.3.0',

  # ML/DL
  'Imbalanced-Learn >= 0.9.1',
  'SciKit-Fuzzy >= 0.4.2',
  'SciKit-Learn >= 0.24.2',   # not latest, for compat w/ Auto-SKLearn
  'TensorFlow >= 2.9.1',

  # Trustworthy AI
  'GraphViz >= 0.20.1',
  'LIME >= 0.2.0.1',
  'SHAP >= 0.36.0',   #  not latest, for compat w/ some other common deps

  # File Systems
  'FSSpec >= 2022.7.1',
  'S3FS >= 2022.7.1',

  # misc/other
  'CLICK >= 8.0.4',   #  not latest, for compat w/ some other common deps
  'Python-DotEnv >= 0.20.0',
  'PyYAML >= 6.0',
  'Ruamel.YAML >= 0.17.21',
  'Tqdm >= 4.64.0',
  'ULID-Py >= 1.1.0',
]


[project.urls]
Homepage = 'https://h1st.ai'
Documentation = 'https://h1st.ai'
GitHub = 'https://github.com/h1st-ai/h1st'
Repository = 'https://github.com/h1st-ai/h1st'


[project.optional-dependencies]
dev = [
]


[build-system]
requires = [
  'SetUpTools >= 65.2.0',
  'Wheel >= 0.37.1',
]
build-backend = 'setuptools.build_meta'
